# Generated by Django 4.1.4 on 2023-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_tcg_api', '0002_alter_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
