# Generated by Django 4.1.4 on 2023-01-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_tcg_api', '0003_alter_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='image', upload_to='card_images'),
            preserve_default=False,
        ),
    ]
