# Generated by Django 4.1.4 on 2022-12-31 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_integrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_integrator.datasource')),
            ],
        ),
    ]
