# Generated by Django 4.1.4 on 2022-12-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integrator', '0002_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
