# Generated by Django 4.1.4 on 2023-01-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integrator', '0003_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='datasource',
        ),
        migrations.AddField(
            model_name='credential',
            name='name',
            field=models.TextField(default='Unnamed'),
            preserve_default=False,
        ),
    ]
