# Generated by Django 4.1.4 on 2023-01-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integrator', '0004_remove_credential_datasource_credential_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='credential',
            name='key',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
