name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pip install -r requirements/dev.txt
      - name: Run tests
        run: python ./manage.py test
    
